import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

interface LayoutProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-900 text-white h-screen`}>
        {children}
      </body>
    </html>
  );
}
